[package]
name = "libptrsx"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "ptrsx"
# crate-type = ["cdylib"]

[dependencies.vmmap]
path = "../vmmap"
default-features = false

[dependencies.bincode]
version = "2.0.0-rc.3"
default-features = false
features = ["derive", "std"]