[package]
name = "inject"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.10"
memoffset = "0.9.0"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.machx]
version = "0.4.4"
default-features = false
