[build]
# target = "aarch64-unknown-linux-musl"
target = "x86_64-unknown-linux-musl"
# target = "aarch64-apple-darwin"

[registries.crates-io]
protocol = "sparse"

[target.aarch64-unknown-linux-musl]
linker = "/Users/keke/.local/cross/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-gcc"
ar = "/Users/keke/.local/cross/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-ar"

[target.x86_64-unknown-linux-musl]
linker = "/Users/keke/.local/cross/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc"
ar = "/Users/keke/.local/cross/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-ar"
