[package]
name = "ptrsx"
version = "0.1.0"
edition = "2021"

[dependencies.vmmap]
path = "../vmmap"
default-features = false

[dependencies.bincode]
version = "2.0.0-rc.3"
default-features = false
features = ["derive", "std"]